export const INFO_LOADING='INFO_LOADING';
export const INFO_FAILED='INFO_FAILED';
export const ADD_INFO='ADD_INFO';
export const LIGHTS_LOADING='LIGHTS_LOADING';
export const LIGHTS_FAILED='LIGHTS_FAILED';
export const ADD_LIGHTS='ADD_LIGHTS';
export const UPDATE_LIGHTS='UPDATE_LIGHTS';
export const UPDATE_KEY='UPDATE_KEY';